<?php

namespace App\Listeners;

use App\Events\DealWon;
use App\Events\PaymentReceived;
use App\Events\InspectionCompleted;
use App\Models\DocumentTemplate;
use App\Services\DocumentTemplateService;
use App\Mail\GeneratedDocumentMail;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Log;

class AutoGenerateDocuments
{
    protected $templateService;

    public function __construct(DocumentTemplateService $templateService)
    {
        $this->templateService = $templateService;
    }

    /**
     * Handle the events.
     */
    public function handle(object $event): void
    {
        $triggerEvent = null;
        $lead = null;
        $sale = null;
        $milestone = null;

        if ($event instanceof DealWon) {
            $triggerEvent = 'deal_won';
            $sale = $event->sale;
            $lead = $sale->lead;
        } elseif ($event instanceof PaymentReceived) {
            $triggerEvent = 'payment_received';
            $milestone = $event->milestone;
            $sale = $milestone->paymentPlan->sale;
            $lead = $sale->lead;
        } elseif ($event instanceof InspectionCompleted) {
            $triggerEvent = 'inspection_completed';
            $lead = $event->inspection->lead;
        }

        if (!$triggerEvent || !$lead) {
            return;
        }

        // Find active templates matching trigger
        $templates = DocumentTemplate::where('is_active', true)
            ->where('trigger_event', $triggerEvent)
            ->get();

        foreach ($templates as $template) {
            try {
                // Compile & generate PDF document
                $doc = $this->templateService->compileAndGenerate($template, $lead, $sale, $milestone);

                // Send email notification to client with PDF attachment link
                if ($lead->email) {
                    Mail::to($lead->email)->send(new GeneratedDocumentMail($doc));
                }

                // Log system activity on Lead profile
                $lead->activities()->create([
                    'user_id' => 1, // System automated user id fallback
                    'activity_type' => 'Document Uploaded',
                    'description' => "Automated document generated: '{$doc->title}' triggered by {$triggerEvent} event.",
                ]);

            } catch (\Exception $e) {
                Log::error("Failed to autogenerate document ID {$template->id} for Lead ID {$lead->id}: " . $e->getMessage());
            }
        }
    }
}
