<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Event;
use Illuminate\Auth\Events\Login;
use Illuminate\Auth\Events\Logout;
use App\Models\ActivityLog;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        \Illuminate\Support\Facades\Event::listen(
            \App\Events\DealWon::class,
            [\App\Listeners\AutoGenerateDocuments::class, 'handle']
        );
        \Illuminate\Support\Facades\Event::listen(
            \App\Events\PaymentReceived::class,
            [\App\Listeners\AutoGenerateDocuments::class, 'handle']
        );
        \Illuminate\Support\Facades\Event::listen(
            \App\Events\InspectionCompleted::class,
            [\App\Listeners\AutoGenerateDocuments::class, 'handle']
        );
    }
}
